set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Simple Plasma Applet for Yandex.Disk.")

set(CPACK_PACKAGE_DESCRIPTION "Simple Plasma Applet for Yandex.Disk.\nThis applet show info about used and total space of your Yandex.Disk account.\n")
set(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION})

set(CPACK_PACKAGE_VENDOR "Vadim Kalinnikov")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/moose-kazan/plasmoid-ydinfo")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/release")

# https://unix.stackexchange.com/a/11552/254512
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")#/${CMAKE_PROJECT_VERSION}")

#set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
#set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
#set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "moose@ylsoftware.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Vadim Kalinnikov")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "plasma-desktop >= 6.0")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "yandex-disk")
set(CPACK_DEBIAN_PACKAGE_SECTION "kde")

set(CPACK_RPM_PACKAGE_LICENSE "LGPL-2.1")
set(CPACK_RPM_PACKAGE_REQUIRES "plasma-desktop >= 6.0")
set(CPACK_RPM_PACKAGE_RECOMMENDS "yandex-disk")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/LGPL-2.1-or-later.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)#ONE_PER_GROUP)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
include(CPack)
